# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://abhijayendra.github.io/
baseurl: /
title: Abhijayendra Singh
author: Abhijayendra Singh
description: Personal blog and resume
avatar: profile.png
email: abhijayendra@gmail.com
github: abhijayendra # username
twitter: abhijayendra
linkedin: abhijayendra
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: 
google_analytics: UA-10595211-3


# needed for travis-ci build
exclude: [vendor]
